Vagrant.configure("2") do |config|
 config.vm.define "nfs-server" do |nfs_server|
 nfs_server.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
 nfs_server.vm.network "private_network", ip: "192.168.57.13"
 nfs_server.vm.hostname = "nfs-server"
 nfs_server.vm.box_version = "2506.0.0"
 nfs_server.vm.provision "shell", path: "nfs-server-setup.sh"
 end
 config.vm.define "master" do |master|
 master.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
 master.vm.network "private_network", ip: "192.168.57.10"
 master.vm.hostname = "master-node"
 master.vm.box_version = "2506.0.0"
 master.vm.provision "shell", path: "master.sh"
 end


 config.vm.define "worker1" do |worker1|
 worker1.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
 worker1.vm.network "private_network", ip: "192.168.57.11"
 worker1.vm.hostname = "worker1"
 worker1.vm.box_version = "2506.0.0"
 worker1.vm.provision "shell", path: "worker.sh"
 end


 config.vm.define "worker2" do |worker2|
 worker2.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
 worker2.vm.network "private_network", ip: "192.168.57.12"
 worker2.vm.hostname = "worker2"
 worker2.vm.box_version = "2506.0.0"
 worker2.vm.provision "shell", path: "worker.sh"
 end


 
end